### ISSUE TITLE
Soll Elektroheizung als weiterer Energieträger verwendet werden?

### ISSUE THREAD

**Issue by Veki22** [nrohrbach/HeizcheckGemeinde#1]

**Comment by nrohrbach** [comment]
Ich habe folgende Codes verwendet:

                                            7500: 'Keine',
                                            7501: 'Weitere',
                                            7510: 'Weitere',
                                            7511: 'Weitere',
                                            7512: 'Weitere',
                                            7513: 'Weitere',
                                            7520: 'Gas',
                                            7530: 'Heizöl',
                                            7540: 'Weitere',
                                            7541: 'Weitere',
                                            7542: 'Weitere',
                                            7543: 'Weitere',
                                            7550: 'Weitere',
                                            7560: 'Elektrizität',
                                            7570: 'Weitere',
                                            7580: 'Weitere',
                                            7581: 'Weitere',
                                            7582: 'Weitere',
                                            7598: 'Unbestimmt',
                                            7599: 'Keine'

**Comment by Veki22** [comment]
Ab bei der Umsetzung in meinen zwei Notebooks bemerkt, dass der Wert 7599 im GWR als "Andere" definiert ist.
Habe somit hier den Wert "Weitere" definiert. Musst du dann bei dir auch noch machen.

Im Notebook sieht es bei mir nun so aus. Habe da noch die Definitionen von GWR aufgeführt. Siehe auf im Ordner Notebooks.

Die Bezeichnungen den Heizcodes zuweisen und als Liste speichern.
Um die finale Visualisierung auf die drei definierten Energiequellen (Gas, Heizöl, Elektrizität) zu fokussieren, werden die Energiequellen zusammengefasst.
Im GWR-Datenfile sind folgende Energiequellen definiert:
7501: 'Luft', 7510: 'Erdwärme (generisch', 7511: 'Erdwärmesonde', 7512: 'Erdregister', 7513: 'Wasser (Grundwasser, Oberflächenwasser, Abwasser)'
7520: 'Gas', 7530: 'Heizöl', 7540: 'Holz (generisch)', 7541: 'Holz (Stückholz)', 7542: 'Holz (Pellets)', 7543: 'Holz (Schnitzel)', 7550: 'Abwärme (innerhalb des Gebäudes)'
 7560: 'Elektrizität', 7570: 'Sonne (thermisch)', 7580: 'Fernwärme (generisch)', 7581: 'Fernwärme (Hochtemperatur)', 7582: 'Fernwärme (Niedertemperatur)'
7598: 'Unbestimmt', 7599: 'Andere'

dfGWRSource['Energiequelle'] = dfGWRSource.Energiequelle.replace({
                                            7500: 'Keine',
                                            7501: 'Weitere',
                                            7510: 'Weitere',
                                            7511: 'Weitere',
                                            7512: 'Weitere',
                                            7513: 'Weitere',
                                            7520: 'Gas',
                                            7530: 'Heizöl',
                                            7540: 'Weitere',
                                            7541: 'Weitere',
                                            7542: 'Weitere',
                                            7543: 'Weitere',
                                            7550: 'Weitere',
                                            7560: 'Elektrizität',
                                            7570: 'Weitere',
                                            7580: 'Weitere',
                                            7581: 'Weitere',
                                            7582: 'Weitere',
                                            7598: 'Unbestimmt',
                                            7599: 'Weitere'                                           
                                            })

**Comment by nrohrbach** [comment]
7500: 'Keine',
                                        7501: 'Weitere',
                                        7510: 'Weitere',
                                        7511: 'Weitere',
                                        7512: 'Weitere',
                                        7513: 'Weitere',
                                        7520: 'Gas',
                                        7530: 'Heizöl',
                                        7540: 'Weitere',
                                        7541: 'Weitere',
                                        7542: 'Weitere',
                                        7543: 'Weitere',
                                        7550: 'Weitere',
                                        7560: 'Elektrizität',
                                        7570: 'Weitere',
                                        7580: 'Weitere',
                                        7581: 'Weitere',
                                        7582: 'Weitere',
                                        7598: 'Unbestimmt',
                                        7599: 'Weitere' (geändert)


und NULL = unbestimmt!

**Comment by nrohrbach** [comment]
Ich habe 7599 in den Notebooks 1.2 und 1.4 angepasst.
