### ISSUE TITLE
Wie gehen wir mit NULL Werten um?

### ISSUE THREAD

**Issue by Veki22** [nrohrbach/HeizcheckGemeinde#4]
Weisen  wie diese aus, oder ordnen wir diese einer Kategorie zu? Ich würde diese wohl separat ausweisen, oder?

**Comment by Veki22** [comment]
Bei der Frage 1.1 habe ich dies mal umgesetzt. NULL = "leer"

**Comment by nrohrbach** [comment]
Gemäss Diskussion vom Montag werden NULL Werte nach "Unbestimmt" gemappt.
