### ISSUE TITLE
Geopackage für Frage 1.3 erstellen

### ISSUE THREAD

**Issue by Veki22** [nrohrbach/HeizcheckGemeinde#5]
Ich konnte mein Geopackage nicht in den Ordner Daten hochladen. Der Upload ist auf 25MB begrenzt. 
Ziel wäre, dass man mit dem Notebook 1.3_Energiequellen_GHE.ipynb des Geopackage täglich erstellt und ich es dann wieder für den WMS-Server herunterlade.

**Comment by nrohrbach** [comment]
Hoi Jürg

Ich habe diese Automatisierung nocheinmal angeschaut. Das Problem ist, dass das File über 100MB ist. Das ist die Limite von Github.

Mein Vorschlag wäre statt ein grosses Geopackage zu schreiben halt 2 oder 3 Geopackages zu erstellen (Filter nach Kantonen). Anschliessend 2 Geopackages mit Github actions hochladen. Die HeatMap geht bestimmt auch mit 2 Inputfiles?

LG Nico

**Comment by nrohrbach** [comment]
oder vielleicht könnten wir das Geopackage auch auf unter 100MB zippen.

**Comment by Veki22** [comment]
Hallo Nico

Habe gerade 2 Files erstellt und erfolgreich getestet. Das Skript hier im Git habe ich abgepasst. Musst mal schauen, ob es nun läuft.

**Comment by nrohrbach** [comment]
Hoi Jürg
Sieht gut aus.
ich habe nun alle Jobs automatisiert. Diese laufen jeweils jede Nacht zwischen 2.00 und 3.30.
Schauen wir am Montag obs geklappt hat :-)

LG Nico

**Comment by Veki22** [comment]
Hallo Nico

Habe gerade den Download und das aktualisieren der GeoPackage Files auf der Server Seite automatisiert.
Der Task läuft täglich um 05:00.
Das aktualisieren der Dateien reicht aus. Ein Neustart vom QGIS-Server Dockerimages ist nicht nötig :-)

![Task_GeoPackage_aktualisieren](https://user-images.githubusercontent.com/111987930/198876863-890853a3-b956-4b80-9520-ad9ef45703e8.png)
