### ISSUE TITLE
1.2 Anzahl Einwohnende: Elektrizität fehlt

### ISSUE THREAD

**Issue by Veki22** [nrohrbach/HeizcheckGemeinde#9]
Hallo Nico

Hier fehlen noch die Elektrizitätsheizungen:
![1 2_Anzahl_Einwohnende](https://user-images.githubusercontent.com/111987930/198880440-1c6fcea5-b8d4-496a-bc56-c7a42dd9e0ba.png)

oder müsste ich noch im Dash-Board was anpassen?

 
### Definition der callback Funktion um die Grafik der gerade ausgewählten Gemeinde zu erstellen
@app.callback(
    Output('personen', 'figure'),
    [Input("Gemeinde-dropdown", "value")]
)

def update_figure3(Gemeinde):
    dfselect3 = dfPax.loc[(dfPax['Gemeinde']==Gemeinde)]
    fig3 = px.bar(dfselect3,
                  x="Energieträger",
                  y= "Anzahl",
                  color="Energieträger",
                  color_discrete_map=FigColor,
                  title='<b> Anteil betroffener Personen pro Energieträger </b>')

Gruss
Jürg

**Comment by nrohrbach** [comment]
Erledigt!
